----------------------------------

      --FUNÇÔES SINGLE ROW--

----------------------------------

-- O que é? --

-- Uma função que retorna um valor para cada linha recuperada/exibida pelo seu SELECT.
-- Há tambem funções de multiple rows onde retornará mais um valor por linha recuperada pelo SELECT.

-- Características --

-- Podem manipular itens de dados
-- Receber argumentos e retornar valor
-- Atuam sobre cada linha retornada
-- Retornam um resultado por linha
-- podem modificar o tipo de dado
-- Podem ser aninhados 
-- Recebem argumentos que podem ser colunas ou expressões

-- Sintaxe --

nome_função [(arg1,agr2,...)]

-- Funções que manipulam caracteres --

-- CASE-CONVERSION FUNCTIONS

-- lower
-- upper
-- initcap

-- CHARACTER-MANIPULATION FUNCTIONS

-- concat
-- substr
-- length
-- instr
-- lpad | rpad
-- trim
-- replace


